/**
 * 货源大厅（询价大厅）页面 Mock 数据
 * 按照 Pixso 画板 30:4665 1:1 补充全字段真实样例
 */

export const transportModeOptions = ['全部', '汽运', '水运', '火运', '联运']
export const businessTypeOptions = ['全部', '普通运输', '集装箱运输']
export const quoteModeOptions = ['全部', '竞价', '抢单']
export const vehicleTypeOptions = ['不限', '厢式', '高栏', '平板']
export const sortTabs = ['最新', '长途', '短途', '价格最优', '零担运输', '整车运输']

export const demoWaybills = [
  {
    id: 'TY2435678901',
    businessType: '普通运输',
    cargoTypeTag: '散货',
    transportMode: '多式联运',
    channelSource: '超好运',
    shipperCompany: '厦门港口物流有限公司',
    tradeCount: 2000,
    shipmentVolume: 10000,
    score: 4.5,
    status: '已承接',
    quoteMode: '抢单',
    priceType: '一口价',
    expectedPrice: '35',
    priceUnit: '吨/元',
    startCity: '福建 福州',
    endCity: '福建 厦门',
    cargoDesc: '煤炭  |  50吨  |  200方  |  无包装',
    timeWindow: '8月10日上午10:00装货 - 8月15日下午10:00卸货',
    vehicleRequirement: '9.6米厢式货车  |  总里程89km',
    publishTime: '2025-08-15 10:00:30',
    countdown: '01:23:45',
  },
  {
    id: 'TY2435678902',
    businessType: '普通运输',
    cargoTypeTag: '散货',
    transportMode: '公路',
    channelSource: '超好运',
    shipperCompany: '厦门港口物流有限公司',
    tradeCount: 2000,
    shipmentVolume: 10000,
    score: 4.5,
    status: '已发布',
    quoteMode: '竞价',
    priceType: '一口价',
    expectedPrice: '35',
    priceUnit: '吨/元',
    startCity: '福建 福州',
    endCity: '福建 厦门',
    cargoDesc: '粮食 | 玉米 | 50吨',
    timeWindow: '8月12日上午09:00装货 - 8月14日下午18:00卸货',
    vehicleRequirement: '13米高栏车  |  总里程120km',
    publishTime: '2025-08-15 10:00:30',
    countdown: '03:12:08',
  },
  {
    id: 'TY2435678903',
    businessType: '集装箱运输',
    cargoTypeTag: '集装箱',
    transportMode: '水路',
    channelSource: '至简平台',
    shipperCompany: '厦门港口物流有限公司',
    tradeCount: 1800,
    shipmentVolume: 8500,
    score: 4.8,
    status: '已发布',
    quoteMode: '竞价',
    priceType: '期望单价',
    expectedPrice: '1200',
    priceUnit: '元/箱',
    startCity: '湖北 武汉',
    endCity: '福建 福州',
    cargoDesc: '普通集装箱 | 20GP | 2箱',
    timeWindow: '8月15日上午10:00装货 - 8月20日下午17:00卸货',
    vehicleRequirement: '散货内河集装箱船  |  总航程650km',
    publishTime: '2025-08-15 10:00:30',
    countdown: '05:40:22',
  },
  {
    id: 'TY2435678904',
    businessType: '普通运输',
    cargoTypeTag: '散货',
    transportMode: '多式联运',
    channelSource: '超好运',
    shipperCompany: '厦门港口物流有限公司',
    tradeCount: 2000,
    shipmentVolume: 10000,
    score: 4.5,
    status: '已承接',
    quoteMode: '抢单',
    priceType: '一口价',
    expectedPrice: '35',
    priceUnit: '吨/元',
    startCity: '福建 福州',
    endCity: '福建 厦门',
    cargoDesc: '粮食 | 玉米 | 50吨',
    timeWindow: '8月10日上午10:00装货 - 8月15日下午10:00卸货',
    vehicleRequirement: '9.6米厢式货车  |  总里程89km',
    publishTime: '2025-08-15 10:00:30',
    countdown: '00:45:10',
  },
  {
    id: 'TY2435678905',
    businessType: '普通运输',
    cargoTypeTag: '散货',
    transportMode: '公路',
    channelSource: '超好运',
    shipperCompany: '厦门港口物流有限公司',
    tradeCount: 2000,
    shipmentVolume: 10000,
    score: 4.5,
    status: '已承接',
    quoteMode: '抢单',
    priceType: '一口价',
    expectedPrice: '35',
    priceUnit: '吨/元',
    startCity: '福建 福州',
    endCity: '福建 厦门',
    cargoDesc: '粮食 | 玉米 | 50吨',
    timeWindow: '8月10日上午10:00装货 - 8月15日下午10:00卸货',
    vehicleRequirement: '9.6米厢式货车  |  总里程89km',
    publishTime: '2025-08-15 10:00:30',
    countdown: '01:10:00',
  },
  {
    id: 'TY2435678906',
    businessType: '普通运输',
    cargoTypeTag: '散货',
    transportMode: '水路',
    channelSource: '至简平台',
    shipperCompany: '厦门港口物流有限公司',
    tradeCount: 2000,
    shipmentVolume: 10000,
    score: 4.5,
    status: '已发布',
    quoteMode: '竞价',
    priceType: '一口价',
    expectedPrice: '35',
    priceUnit: '吨/元',
    startCity: '福建 福州',
    endCity: '福建 厦门',
    cargoDesc: '粮食 | 玉米 | 50吨',
    timeWindow: '8月10日上午10:00装货 - 8月15日下午10:00卸货',
    vehicleRequirement: '9.6米厢式货车  |  总里程89km',
    publishTime: '2025-08-15 10:00:30',
    countdown: '02:30:15',
  }
]
